project:
  type: website
  output-dir: docs

website:
  title: "My example website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Assignments"
        menu:
          - ae01-unvotes.qmd
    right:
      - icon: github
        href: https://github.com/avirdi1
  page-footer:
    left: "© 2026 Anmol Virdi"
    right: "Built with Quarto"
    
format:
  html:
    theme:
      - vapor
      - brand
    css: styles.css
    toc: true



